### ISSUE TITLE
Cant get the program to start as it says 

### ISSUE THREAD

**Issue by slider6996** [Roland-J/SmartSkillup#10]
## Describe the bug
<Cant get the program to start, pasted in proper folder and type in game "//lua l smartskillup" but just says Error loading smartskillup: file does not exist. Thats whats in the log.

I am on Horizonxi if that matters but i use windower just fine with horizonxi so would think this would work as i downloaded another older skillup lua and it works but very buggy and stops working so not sure why this one wont load at all :/ -->

## Steps to Reproduce
<!-- Steps to reproduce the behavior:
Put file into Addons Folder ( i also tried plugins to just see ) 
type //lua l smartskillup and error pops up

## Expected behavior
Lua file to load and show ui or hud :) 

Maybe its something im missing or extra i need to do but i dont see no one else saying this in bug area so maybe im missing something?

**Comment by slider6996** [comment]
![error3](https://github.com/Roland-J/SmartSkillup/assets/77522568/624ec3ba-a89c-443e-a47f-4f6064f6cc11)

**Comment by GODsAssassin767** [comment]
> ## Describe the bug
> <Cant get the program to start, pasted in proper folder and type in game "//lua l smartskillup" but just says Error loading smartskillup: file does not exist. Thats whats in the log.
> 
> I am on Horizonxi if that matters but i use windower just fine with horizonxi so would think this would work as i downloaded another older skillup lua and it works but very buggy and stops working so not sure why this one wont load at all :/ -->
> 
> ## Steps to Reproduce

the downloaded file is SmartSkillup-main, rename the file to SmartSkillup without the -main and it will worked. it worked for me when i did it because i just downloaded it an hour ago

**Comment by slider6996** [comment]
> > ## Describe the bug
> > <Cant get the program to start, pasted in proper folder and type in game "//lua l smartskillup" but just says Error loading smartskillup: file does not exist. Thats whats in the log.
> > I am on Horizonxi if that matters but i use windower just fine with horizonxi so would think this would work as i downloaded another older skillup lua and it works but very buggy and stops working so not sure why this one wont load at all :/ -->
> > ## Steps to Reproduce
> 
> the downloaded file is SmartSkillup-main, rename the file to SmartSkillup without the -main and it will worked. it worked for me when i did it because i just downloaded it an hour ago

Hey u were correct, i never even thought about that....appreciate the help man, thank you so much.
